### ISSUE TITLE
Which QEMU version worked

### ISSUE THREAD

**Issue by yf13** [diodesign/diosix#22]
Thanks for sharing this! So may I know which version of QEMU was checked before?

I downloaded `diosix-0.0.2-debug-20210404` release and tried with the stock QEMU v6.2 on my Ubuntu 22.04 PC, but it seems not working -- nothing from console and the fan of the PC fan keeps making nosies, I have to forcedly terminate it.

```shell
$ qemu-system-riscv64 --version
QEMU emulator version 6.2.0 (Debian 1:6.2+dfsg-2ubuntu6.22)
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
$ qemu-system-riscv64  -M virt -m 1G -smp 2 -nographic -bios ~/Downloads/diosix-0.0.2-debug-20210404
QEMU: Terminated
```
Then from GDB I saw:

```
(gdb) i threads
  Id   Target Id                    Frame
* 1    Thread 1.1 (CPU#0 [halted ]) 0x0000000080000096 in infinite_loop ()
  2    Thread 1.2 (CPU#1 [running]) core::cell::UnsafeCell<u8>::get<u8> (self=0x2) at /home/chris/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cell.rs:1862
(gdb) bt
#0  0x0000000080000096 in infinite_loop ()
#1  0x0000000080000092 in clear_bss_loop_end ()
```

**Comment by diodesign** [comment]
Hey, we've ported the project to Zig. And we need Qemu 10.1.5 or higher, as now documented.
